### ISSUE TITLE
Bump packages and maintain?

### ISSUE THREAD

**Issue by binarykitchen** [ariporad/is-ascii#1]
Just wondering ... cos we might need it if it's at least maintained ...

**Comment by ariporad** [comment]
Hi @binarykitchen,

I'm not quite sure what you mean. This module is extremely simple and doesn't really require any maintenance or updates. Is there a specific issue you're encountering?

**Comment by binarykitchen** [comment]
@ariporad In general I agree with you. Only two dev dependencies although sometimes dev dependencies still can carry vulnerabilities. 

Nothing really needed although with the high security settings for the company I am working for, we do question this. Especially if the maintainer is still here and hasn't abandoned the project. And this seems to be the case, you are still here 👍
